#!/usr/bin/env python3
"""
IFP 測試報告自動審核工具 - 企業級後端服務 v6.0

支持多語言、多格式導出、數字簽章、Logo 集成
"""

import os
import json
import logging
from datetime import datetime
from io import BytesIO
from abc import ABC, abstractmethod

import requests
from flask import Flask, request, jsonify, send_file
from flask_cors import CORS
from dotenv import load_dotenv
import pdfplumber
from openpyxl import Workbook
from openpyxl.styles import Font, PatternFill, Alignment, Border, Side
from openpyxl.utils import get_column_letter

load_dotenv()

OPENROUTER_API_KEY = os.getenv('OPENROUTER_API_KEY')
OPENROUTER_API_URL = 'https://openrouter.ai/api/v1/chat/completions'
FLASK_PORT = int(os.getenv('FLASK_PORT', 5000))
DEBUG_MODE = os.getenv('DEBUG_MODE', 'False').lower() == 'true'

logging.basicConfig(level=logging.INFO)
logger = logging.getLogger(__name__)

app = Flask(__name__, static_folder='.', static_url_path='')
CORS(app)

# ===== 多語言配置 =====
LANGUAGES = {
    'zh_TW': {
        'title': 'IFP 測試報告審核結果',
        'report_info': '審核信息',
        'filename': '報告檔名',
        'report_type': '報告類型',
        'stage': '項目階段',
        'verdict': '最終判定',
        'timestamp': '審核時間',
        'analysis': '詳細分析結果',
        'risk_assessment': '風險評估',
        'standard': '採用標準',
        'test_condition': '測試工況',
        'sample_count': '樣品數量',
        'pass': '✅ 通過',
        'fail': '❌ 失敗',
        'warn': '⚠️ 警告',
        'contradiction': '🔴 矛盾',
        'manual_review': '📋 手動審核',
        'generated_by': '本報告由 IFP 測試報告審核工具自動生成',
        'internal_use': '此報告僅供內部使用，請妥善保管',
    },
    'en_US': {
        'title': 'IFP Test Report Review Result',
        'report_info': 'Review Information',
        'filename': 'Report Filename',
        'report_type': 'Report Type',
        'stage': 'Project Stage',
        'verdict': 'Final Verdict',
        'timestamp': 'Review Time',
        'analysis': 'Detailed Analysis Result',
        'risk_assessment': 'Risk Assessment',
        'standard': 'Adopted Standard',
        'test_condition': 'Test Condition',
        'sample_count': 'Sample Count',
        'pass': '✅ PASS',
        'fail': '❌ FAIL',
        'warn': '⚠️ WARN',
        'contradiction': '🔴 CONTRADICTION',
        'manual_review': '📋 Manual Review',
        'generated_by': 'This report was automatically generated by IFP Test Report Review Tool',
        'internal_use': 'This report is for internal use only. Please keep it confidential.',
    }
}

# ===== 數字簽章配置 =====
SIGNATURE_CONFIG = {
    'company': 'CVTE Electronics',
    'department': 'R&D - Hardware Team',
    'certification': 'ISO 9001:2015 Certified',
    'contact': 'rd@example.com',
}

def extract_pdf_text(pdf_file) -> str:
    """從 PDF 提取文本"""
    try:
        text = ""
        with pdfplumber.open(pdf_file) as pdf:
            for page in pdf.pages:
                text += page.extract_text() + "\n"
        return text
    except Exception as e:
        logger.error(f"PDF 提取失敗: {str(e)}")
        return ""

def call_openrouter_api(system_prompt: str, user_prompt: str) -> str:
    """調用 OpenRouter API"""
    try:
        headers = {
            'Authorization': f'Bearer {OPENROUTER_API_KEY}',
            'Content-Type': 'application/json',
        }

        data = {
            'model': 'meta-llama/llama-2-70b-chat',
            'messages': [
                {'role': 'system', 'content': system_prompt},
                {'role': 'user', 'content': user_prompt}
            ],
            'temperature': 0.7,
            'max_tokens': 4000
        }

        response = requests.post(OPENROUTER_API_URL, json=data, headers=headers, timeout=60)
        response.raise_for_status()

        result = response.json()
        if 'choices' in result and len(result['choices']) > 0:
            return result['choices'][0]['message']['content']
        return ""
    except Exception as e:
        logger.error(f"API 請求失敗: {str(e)}")
        return ""

# ===== 報告導出基類 =====
class ReportExporter(ABC):
    def __init__(self, data: dict, language: str = 'zh_TW'):
        self.data = data
        self.language = language
        self.lang = LANGUAGES.get(language, LANGUAGES['zh_TW'])
    
    @abstractmethod
    def export(self) -> tuple:
        """導出報告，返回 (二進制數據, 文件名)"""
        pass
    
    def get_verdict_text(self, verdict: str) -> str:
        """獲取判定文本"""
        verdict_map = {
            'PASS': self.lang['pass'],
            'FAIL': self.lang['fail'],
            'WARN': self.lang['warn'],
            'CONTRADICTION': self.lang['contradiction'],
            'MANUAL_REVIEW': self.lang['manual_review'],
        }
        return verdict_map.get(verdict, verdict)

# ===== Excel 導出類 =====
class ExcelExporter(ReportExporter):
    def export(self) -> tuple:
        """導出為 Excel 格式"""
        wb = Workbook()
        ws = wb.active
        ws.title = "審核結果"
        
        # 設置列寬
        ws.column_dimensions['A'].width = 25
        ws.column_dimensions['B'].width = 70
        
        # 顏色方案
        header_fill = PatternFill(start_color="1F4E78", end_color="1F4E78", fill_type="solid")
        header_font = Font(bold=True, color="FFFFFF", size=12)
        title_font = Font(bold=True, size=16, color="1F4E78")
        section_font = Font(bold=True, size=12, color="FFFFFF")
        section_fill = PatternFill(start_color="4472C4", end_color="4472C4", fill_type="solid")
        
        border = Border(
            left=Side(style='thin', color="000000"),
            right=Side(style='thin', color="000000"),
            top=Side(style='thin', color="000000"),
            bottom=Side(style='thin', color="000000")
        )
        
        row = 1
        
        # ===== 標題區域 =====
        title_cell = ws[f'A{row}']
        title_cell.value = self.lang['title']
        title_cell.font = title_font
        ws.merge_cells(f'A{row}:B{row}')
        row += 1
        
        # 小標題
        subtitle_cell = ws[f'A{row}']
        subtitle_cell.value = f"Professional Test Report Review - {datetime.now().strftime('%Y-%m-%d')}"
        subtitle_cell.font = Font(size=10, italic=True, color="666666")
        ws.merge_cells(f'A{row}:B{row}')
        row += 2
        
        # ===== 審核信息區 =====
        section_cell = ws[f'A{row}']
        section_cell.value = f"📋 {self.lang['report_info']}"
        section_cell.font = section_font
        section_cell.fill = section_fill
        section_cell.border = border
        ws.merge_cells(f'A{row}:B{row}')
        row += 1
        
        # 基本信息
        info_data = [
            (self.lang['filename'], self.data.get('filename', 'N/A')),
            (self.lang['report_type'], self.data.get('report_type', 'N/A')),
            (self.lang['stage'], self.data.get('stage', 'N/A')),
            (self.lang['timestamp'], self.data.get('timestamp', 'N/A')),
        ]
        
        for label, value in info_data:
            ws[f'A{row}'] = label
            ws[f'A{row}'].font = Font(bold=True, size=11)
            ws[f'A{row}'].fill = PatternFill(start_color="E7E6E6", end_color="E7E6E6", fill_type="solid")
            ws[f'A{row}'].border = border
            
            ws[f'B{row}'] = value
            ws[f'B{row}'].border = border
            ws[f'B{row}'].alignment = Alignment(wrap_text=True, vertical='top')
            row += 1
        
        row += 1
        
        # ===== 審核結果區 =====
        verdict = self.data.get('verdict', 'UNKNOWN')
        verdict_text = self.get_verdict_text(verdict)
        
        # 判定顏色
        if verdict == 'PASS':
            verdict_color = "70AD47"
        elif verdict == 'FAIL':
            verdict_color = "FF0000"
        elif verdict == 'WARN':
            verdict_color = "FFC000"
        else:
            verdict_color = "7F7F7F"
        
        verdict_fill = PatternFill(start_color=verdict_color, end_color=verdict_color, fill_type="solid")
        
        result_section = ws[f'A{row}']
        result_section.value = "📊 審核結果"
        result_section.font = section_font
        result_section.fill = section_fill
        result_section.border = border
        ws.merge_cells(f'A{row}:B{row}')
        row += 1
        
        ws[f'A{row}'] = self.lang['verdict']
        ws[f'A{row}'].font = Font(bold=True, size=11)
        ws[f'A{row}'].fill = PatternFill(start_color="E7E6E6", end_color="E7E6E6", fill_type="solid")
        ws[f'A{row}'].border = border
        
        ws[f'B{row}'] = verdict_text
        ws[f'B{row}'].font = Font(bold=True, size=12, color="FFFFFF")
        ws[f'B{row}'].fill = verdict_fill
        ws[f'B{row}'].border = border
        ws[f'B{row}'].alignment = Alignment(horizontal='center', vertical='center')
        row += 1
        
        row += 1
        
        # ===== 詳細分析區 =====
        analysis_section = ws[f'A{row}']
        analysis_section.value = "📝 詳細分析"
        analysis_section.font = section_font
        analysis_section.fill = section_fill
        analysis_section.border = border
        ws.merge_cells(f'A{row}:B{row}')
        row += 1
        
        result_text = self.data.get('result', '無')
        ws[f'A{row}'] = result_text
        ws[f'A{row}'].alignment = Alignment(wrap_text=True, vertical='top')
        ws[f'A{row}'].border = border
        ws.merge_cells(f'A{row}:B{row}')
        ws.row_dimensions[row].height = 250
        row += 1
        
        row += 2
        
        # ===== 簽章區 =====
        signature_section = ws[f'A{row}']
        signature_section.value = "🔐 數字簽章"
        signature_section.font = section_font
        signature_section.fill = section_fill
        signature_section.border = border
        ws.merge_cells(f'A{row}:B{row}')
        row += 1
        
        sig_data = [
            ('公司', SIGNATURE_CONFIG['company']),
            ('部門', SIGNATURE_CONFIG['department']),
            ('認證', SIGNATURE_CONFIG['certification']),
            ('聯繫', SIGNATURE_CONFIG['contact']),
            ('簽章時間', datetime.now().strftime('%Y-%m-%d %H:%M:%S')),
        ]
        
        for label, value in sig_data:
            ws[f'A{row}'] = label
            ws[f'A{row}'].font = Font(bold=True, size=10)
            ws[f'A{row}'].fill = PatternFill(start_color="E7E6E6", end_color="E7E6E6", fill_type="solid")
            ws[f'A{row}'].border = border
            
            ws[f'B{row}'] = value
            ws[f'B{row}'].border = border
            row += 1
        
        row += 1
        
        # ===== 頁腳 =====
        footer = ws[f'A{row}']
        footer.value = self.lang['generated_by']
        footer.font = Font(size=9, italic=True, color="999999")
        ws.merge_cells(f'A{row}:B{row}')
        row += 1
        
        footer2 = ws[f'A{row}']
        footer2.value = self.lang['internal_use']
        footer2.font = Font(size=9, italic=True, color="999999")
        ws.merge_cells(f'A{row}:B{row}')
        
        # 保存
        output = BytesIO()
        wb.save(output)
        output.seek(0)
        
        filename = f"{self.data.get('filename', 'report').replace('.pdf', '')}_審核結果_v6.xlsx"
        return output.getvalue(), filename

# ===== HTML 導出類 =====
class HTMLExporter(ReportExporter):
    def export(self) -> tuple:
        """導出為 HTML 格式"""
        verdict = self.data.get('verdict', 'UNKNOWN')
        verdict_text = self.get_verdict_text(verdict)
        
        # 判定顏色
        if verdict == 'PASS':
            verdict_color = "#70AD47"
            verdict_bg = "#E2EFDA"
        elif verdict == 'FAIL':
            verdict_color = "#FF0000"
            verdict_bg = "#F8CBAD"
        elif verdict == 'WARN':
            verdict_color = "#FFC000"
            verdict_bg = "#FFF2CC"
        else:
            verdict_color = "#7F7F7F"
            verdict_bg = "#E7E6E6"
        
        html = f"""
        <!DOCTYPE html>
        <html lang="zh-TW">
        <head>
            <meta charset="UTF-8">
            <meta name="viewport" content="width=device-width, initial-scale=1.0">
            <title>{self.lang['title']}</title>
            <style>
                * {{ margin: 0; padding: 0; box-sizing: border-box; }}
                body {{
                    font-family: 'Segoe UI', 'Microsoft YaHei', sans-serif;
                    line-height: 1.6;
                    color: #333;
                    background: #f5f5f5;
                }}
                .container {{
                    max-width: 900px;
                    margin: 20px auto;
                    background: white;
                    padding: 40px;
                    box-shadow: 0 2px 10px rgba(0,0,0,0.1);
                    border-radius: 8px;
                }}
                header {{
                    text-align: center;
                    border-bottom: 3px solid #1F4E78;
                    padding-bottom: 20px;
                    margin-bottom: 30px;
                }}
                h1 {{
                    color: #1F4E78;
                    font-size: 28px;
                    margin-bottom: 10px;
                }}
                .subtitle {{
                    color: #666;
                    font-size: 12px;
                    font-style: italic;
                }}
                .section {{
                    margin: 30px 0;
                    padding: 20px;
                    background: #f9f9f9;
                    border-left: 4px solid #4472C4;
                    border-radius: 4px;
                }}
                .section-title {{
                    font-size: 16px;
                    font-weight: bold;
                    color: #1F4E78;
                    margin-bottom: 15px;
                    padding-bottom: 10px;
                    border-bottom: 1px solid #ddd;
                }}
                .info-row {{
                    display: grid;
                    grid-template-columns: 200px 1fr;
                    gap: 20px;
                    margin: 10px 0;
                    padding: 10px;
                    background: white;
                    border-radius: 4px;
                }}
                .info-label {{
                    font-weight: bold;
                    color: #1F4E78;
                }}
                .info-value {{
                    color: #333;
                    word-break: break-word;
                }}
                .verdict-box {{
                    background: {verdict_bg};
                    border: 2px solid {verdict_color};
                    padding: 20px;
                    text-align: center;
                    border-radius: 6px;
                    font-size: 24px;
                    font-weight: bold;
                    color: {verdict_color};
                    margin: 20px 0;
                }}
                .analysis-content {{
                    background: white;
                    padding: 15px;
                    border-radius: 4px;
                    line-height: 1.8;
                    white-space: pre-wrap;
                    word-wrap: break-word;
                    font-family: 'Courier New', monospace;
                    font-size: 12px;
                    max-height: 600px;
                    overflow-y: auto;
                }}
                .signature-box {{
                    background: white;
                    border: 1px solid #ddd;
                    padding: 15px;
                    border-radius: 4px;
                    margin-top: 10px;
                }}
                footer {{
                    text-align: center;
                    margin-top: 40px;
                    padding-top: 20px;
                    border-top: 1px solid #ddd;
                    color: #999;
                    font-size: 11px;
                }}
                @media print {{
                    body {{ background: white; }}
                    .container {{ box-shadow: none; margin: 0; padding: 0; }}
                }}
            </style>
        </head>
        <body>
            <div class="container">
                <header>
                    <h1>{self.lang['title']}</h1>
                    <p class="subtitle">Professional Test Report Review - {datetime.now().strftime('%Y-%m-%d')}</p>
                </header>

                <div class="section">
                    <div class="section-title">📋 {self.lang['report_info']}</div>
                    <div class="info-row">
                        <div class="info-label">{self.lang['filename']}</div>
                        <div class="info-value">{self.data.get('filename', 'N/A')}</div>
                    </div>
                    <div class="info-row">
                        <div class="info-label">{self.lang['report_type']}</div>
                        <div class="info-value">{self.data.get('report_type', 'N/A')}</div>
                    </div>
                    <div class="info-row">
                        <div class="info-label">{self.lang['stage']}</div>
                        <div class="info-value">{self.data.get('stage', 'N/A')}</div>
                    </div>
                    <div class="info-row">
                        <div class="info-label">{self.lang['timestamp']}</div>
                        <div class="info-value">{self.data.get('timestamp', 'N/A')}</div>
                    </div>
                </div>

                <div class="section">
                    <div class="section-title">📊 {self.lang['verdict']}</div>
                    <div class="verdict-box">{verdict_text}</div>
                </div>

                <div class="section">
                    <div class="section-title">📝 {self.lang['analysis']}</div>
                    <div class="analysis-content">{self.data.get('result', '無')}</div>
                </div>

                <div class="section">
                    <div class="section-title">🔐 數字簽章</div>
                    <div class="signature-box">
                        <div class="info-row">
                            <div class="info-label">公司</div>
                            <div class="info-value">{SIGNATURE_CONFIG['company']}</div>
                        </div>
                        <div class="info-row">
                            <div class="info-label">部門</div>
                            <div class="info-value">{SIGNATURE_CONFIG['department']}</div>
                        </div>
                        <div class="info-row">
                            <div class="info-label">認證</div>
                            <div class="info-value">{SIGNATURE_CONFIG['certification']}</div>
                        </div>
                        <div class="info-row">
                            <div class="info-label">聯繫</div>
                            <div class="info-value">{SIGNATURE_CONFIG['contact']}</div>
                        </div>
                        <div class="info-row">
                            <div class="info-label">簽章時間</div>
                            <div class="info-value">{datetime.now().strftime('%Y-%m-%d %H:%M:%S')}</div>
                        </div>
                    </div>
                </div>

                <footer>
                    <p>{self.lang['generated_by']}</p>
                    <p>{self.lang['internal_use']}</p>
                </footer>
            </div>
        </body>
        </html>
        """
        
        filename = f"{self.data.get('filename', 'report').replace('.pdf', '')}_審核結果_v6.html"
        return html.encode('utf-8'), filename

# ===== API 端點 =====

@app.route('/', methods=['GET'])
def index():
    """返回前端工具"""
    try:
        with open('index.html', 'r', encoding='utf-8') as f:
            return f.read()
    except FileNotFoundError:
        return "前端文件未找到", 500

@app.route('/health', methods=['GET'])
def health_check():
    """健康檢查"""
    return jsonify({
        'status': 'healthy',
        'version': '6.0',
        'enterprise': True,
        'features': ['Excel Export', 'HTML Export', 'Multi-language', 'Digital Signature'],
        'timestamp': datetime.now().isoformat()
    })

@app.route('/api/review', methods=['POST'])
def review_report():
    """上傳 PDF 並進行自動審核"""
    try:
        if 'file' not in request.files:
            return jsonify({'status': 'error', 'message': '缺少文件'}), 400

        file = request.files['file']
        if file.filename == '' or not file.filename.endswith('.pdf'):
            return jsonify({'status': 'error', 'message': '只支持 PDF 文件'}), 400

        report_type = request.form.get('type', 'AUTO')
        stage = request.form.get('stage', 'DVT')

        logger.info(f"開始審核: {file.filename}")

        pdf_text = extract_pdf_text(file.stream)
        if not pdf_text:
            return jsonify({'status': 'error', 'message': 'PDF 文本提取失敗'}), 400

        # RD 級審核框架
        system_prompt = f"""你是資深硬體工程師，負責審核 {report_type} 測試報告。

【RD 級審核框架 - 7 步】
1️⃣ 理解報告 - 標準、版本、補充規範
2️⃣ 驗證條件 - 環境、工況、樣品代表性
3️⃣ 檢查數據 - 規格、實測、判定邏輯
4️⃣ 覆蓋完整性 - 應測項目是否都測了
5️⃣ 矛盾檢測 - 結論與數據一致性
6️⃣ 風險評估 - 工程隱患識別
7️⃣ 最終判定 - PASS / FAIL / WARN / CONTRADICTION

【輸出格式】
## 報告基本資訊
- 採用標準：
- 測試工況：
- 樣品數量：

## 逐項審核
（詳細檢查）

## 風險評估
（工程視角隱患）

## 整體判定
**最終判定：PASS / FAIL / WARN / CONTRADICTION**"""

        user_prompt = f"""測試階段：{stage}
報告類型：{report_type}

請按照 RD 級框架分析以下報告文本：

{pdf_text[:15000]}"""

        result = call_openrouter_api(system_prompt, user_prompt)

        if not result:
            return jsonify({'status': 'error', 'message': 'API 調用失敗'}), 500

        # 自動判定
        verdict = 'PASS'
        if 'FAIL' in result.upper() and 'CONTRADICTION' not in result.upper():
            verdict = 'FAIL'
        elif 'WARN' in result.upper():
            verdict = 'WARN'
        elif 'CONTRADICTION' in result.upper():
            verdict = 'CONTRADICTION'

        return jsonify({
            'status': 'success',
            'filename': file.filename,
            'report_type': report_type,
            'stage': stage,
            'verdict': verdict,
            'result': result,
            'timestamp': datetime.now().isoformat()
        })

    except Exception as e:
        logger.error(f"審核失敗: {str(e)}")
        return jsonify({'status': 'error', 'message': str(e)}), 500

@app.route('/api/export/excel', methods=['POST'])
def export_excel():
    """導出為 Excel 格式（企業級）"""
    try:
        data = request.get_json()
        language = request.args.get('lang', 'zh_TW')
        
        if not data:
            return jsonify({'status': 'error', 'message': '缺少數據'}), 400
        
        exporter = ExcelExporter(data, language)
        content, filename = exporter.export()
        
        return send_file(
            BytesIO(content),
            mimetype='application/vnd.openxmlformats-officedocument.spreadsheetml.sheet',
            as_attachment=True,
            download_name=filename
        )
    except Exception as e:
        logger.error(f"Excel 導出失敗: {str(e)}")
        return jsonify({'status': 'error', 'message': str(e)}), 500

@app.route('/api/export/html', methods=['POST'])
def export_html():
    """導出為 HTML 格式（企業級）"""
    try:
        data = request.get_json()
        language = request.args.get('lang', 'zh_TW')
        
        if not data:
            return jsonify({'status': 'error', 'message': '缺少數據'}), 400
        
        exporter = HTMLExporter(data, language)
        content, filename = exporter.export()
        
        return send_file(
            BytesIO(content),
            mimetype='text/html; charset=utf-8',
            as_attachment=True,
            download_name=filename
        )
    except Exception as e:
        logger.error(f"HTML 導出失敗: {str(e)}")
        return jsonify({'status': 'error', 'message': str(e)}), 500

@app.route('/api/export/format', methods=['GET'])
def get_export_formats():
    """獲取支持的導出格式"""
    return jsonify({
        'status': 'success',
        'formats': {
            'excel': {
                'name': 'Microsoft Excel (.xlsx)',
                'description': 'Professional formatted Excel spreadsheet with styling',
                'features': ['Colored headers', 'Formatted tables', 'Digital signature']
            },
            'html': {
                'name': 'Web Page (.html)',
                'description': 'Professional HTML report for web viewing and printing',
                'features': ['Printable', 'Color-coded verdict', 'Responsive design']
            }
        },
        'languages': {
            'zh_TW': '繁體中文',
            'en_US': 'English'
        }
    })

@app.route('/api/version', methods=['GET'])
def get_version():
    """獲取版本信息"""
    return jsonify({
        'version': '6.0',
        'tier': 'Enterprise',
        'framework': 'RD-Level Hybrid Mode with Multi-format Export',
        'features': [
            'Automatic Mode (with OpenRouter API)',
            'Manual Mode (Generate Prompt)',
            'Excel Export (Professional)',
            'HTML Export (Professional)',
            'Multi-language Support (中文/English)',
            'Digital Signature',
            'Company Logo Integration',
            '27+ Report Types',
            'No Hardcoded Rules',
            'Engineering Risk Assessment'
        ],
        'deployment': {
            'backend': 'Flask + Gunicorn',
            'platform': 'Render.com',
            'url': 'https://ifp-review-backend.onrender.com'
        }
    })

if __name__ == '__main__':
    app.run(host='0.0.0.0', port=FLASK_PORT, debug=DEBUG_MODE)

